# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - angular-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/abhiryan//
        username: ${{ secrets.AzureAppService_ContainerUsername_55b93224d4784ef18cf04ab97569383d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d4d6191d95334e22a616b300a3196855 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/abhiryan//${{ secrets.AzureAppService_ContainerUsername_55b93224d4784ef18cf04ab97569383d }}/personal-plug-site-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'angular-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0264f682e3eb4a1a839e0fa4f2586ecf }}
        images: 'ghcr.io/abhiryan//${{ secrets.AzureAppService_ContainerUsername_55b93224d4784ef18cf04ab97569383d }}/personal-plug-site-frontend:${{ github.sha }}'